config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [ :new, :create, :show, :index ] do 
    resources :doses, only: [ :new, :create ]
    resources :reviews
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :comment, presence: true
  RATING = [1, 2, 3, 4, 5]
  validates :rating, inclusion: {
    in: RATING,
    message: "must be between 1 and 5"
  }

  def stars_as_percent
    (rating / 5.0) * 100.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def new 
    @cocktail = Cocktail.new
  end

  def create 
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def show 
    @cocktail = Cocktail.find(params[:id])
  end

  private 
  
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, except: [ :destroy ]
  
  def new 
    @dose = Dose.new
  end

  def create 
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def find_cocktail 
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_cocktail

  def index
    @cocktail = Cocktail.find(params[:cocktail_id])
    @reviews = @cocktail.reviews
  end

  def new
    @review = @cocktail.reviews.new
  end

  def create
    
    @review = @cocktail.reviews.new(review_params)

    if @review.save 
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private 

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<style>
  .container {
    
    display: grid;
    grid-gap: 10px;
    grid-template-columns: repeat(3, 1fr);
    width: 960px;
    margin: 10px auto;
  }

  .card {
    padding: 10px;
  }

  .card-body {
    background-color: #DBD9D8;
   
  }
  
</style>

<section class="container">
 <% @cocktails.each do |cocktail| %>
  <div class="card col-lg-12 col-sm-6 mx-auto" style="width: 18rem;">
    <img src="https://source.unsplash.com/200x200/?cocktails/" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= cocktail.name %></h5>
      <%= link_to "Cocktail Details", cocktail_path(cocktail), class: "btn btn-primary btn-lg" %>
    </div>
  </div>
  <% end %>
</section>

  

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h1>Create a new cocktail</h1>
            <%= simple_form_for @cocktail do |f| %>
              <%= f.input :name %>
              <%= f.submit class: 'btn btn-primary btn-lg' %>
              <%= link_to "All cocktails", root_path, class: "btn btn-primary btn-lg" %>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<style>
ul {
  list-style: none;
  padding-left: 0;
}

</style>
<br>
<div class="container">
  <div class="row">

  </div>

  <h1><%= @cocktail.name %></h1>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= link_to  "Add a dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary btn-lg" %> 
  <%= link_to "Leave review", new_cocktail_review_path(@cocktail), class: "btn btn-primary btn-lg" %>
<section>
  <br>
  <ul>
  <h1>Reviews for <%= @cocktail.name %></h1>
    <% @cocktail.reviews.each do |review| %>
      <li>
        <%= pluralize(review.rating, 'star') %>:
        <%= render "shared/stars", percent: review.stars_as_percent %>
        <%= review.comment %>
        <p>
          <%= time_ago_in_words(review.created_at) %> ago
        </p>
      </li>
    <% end %>
  </ul>
</section>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h1>Create a new cocktail</h1>
            <%= simple_form_for [@cocktail, @dose] do |f| %>
              <%= f.input :description %>
              <%= f.association :ingredient  %>
              <%= f.submit class: 'btn btn-primary btn-lg' %>
              <%= link_to "All cocktails", root_path, class: "btn btn-primary btn-lg" %>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <style>
    .banner {
    text-align: center;
    padding-top: 20px;
    color: white;
    height: 200px;
    }
    </style>
  </head>

  <body>
  <header>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'cocktails.jpg' %>');">
  <div class="banner-content">
    <h1>Le Wagon's cocktails</h1>
    <p>Awesome beverages for developers nightlife</p>
    <%= link_to "All cocktails", root_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

  </header>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<style>
  ul {
  list-style: none;
  }
</style>
<h1>Reviews for <%= link_to @cocktail.name, @cocktail %></h1>
<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= pluralize(review.rating, 'star') %>:
      <%= render "shared/stars", percent: review.stars_as_percent %>
      <%= review.comment %>
      <p>
        <%= time_ago_in_words(review.created_at) %> ago
      </p>
      <hr>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="row justify-content-center">
        <div class="col-md-8">
        <br>
          <h3>New Review for <%= link_to @cocktail.name, @cocktail %></h3>
            <%= simple_form_for [@cocktail, @review] do |f| %>
              <%= f.input :comment %>
              <%= f.input :rating %>
              <%= f.submit class: 'btn btn-primary btn-lg' %>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_stars.html.erb
<style>
  .star-rating {
	display: flex;
	align-items: center;
	font-size: 25px;
	height: 25px;
  justify-content: left;
  }

	.back-stars {
		display: flex;
		color: #c2c2c2;
		position: relative;
		// text-shadow: 0px 1px 0 #a2a2a2;
	}
	.front-stars {
		display: flex;
		color: #E8890C;
		overflow: hidden;
		position: absolute;
		top: 0;
	}
}
</style>

<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>